### ISSUE TITLE
README (pihole_FTL_API.sh) and filename for query_FTL_API.sh differ

### ISSUE THREAD

**Issue by thomasmerz** [yubiuser/pihole_tools#1]
* Either the README should point to `query_FTL_API.sh` (and `pihole_FTL_API.md` should be renamed)  
* or `query_FTL_API.sh` should be renamed to `pihole_FTL_API.sh`.

**Comment by yubiuser** [comment]
Fixed by https://github.com/yubiuser/pihole_tools/commit/7d9525f32d0b0348c63a218f33a1c3bcecd15682

You see how undecided I was regarding the name.
